@echo off
mkdir msvc
cd msvc
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DARROW_DEPENDENCY_SOURCE=BUNDLED ^
    -DARROW_BUILD_SHARED=ON -DARROW_BUILD_STATIC=ON ^
    -DARROW_WITH_LZ4=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_ZSTD=ON ..
cmake --build . --config Release
pause